Repository rocky-linux/os-autoinst-distri-rocky, pull requests merged in 2022-07, with the labels that each got.

#124 Switch to ide-hd as ide-drive got removed
  templates.fif.json
Labels: test suite

#125 Add minimal and desktop false to all incorrect tests in universal
  templates.fif.json
Labels: type: bug, test suite

#127 feat: set DESKTOP=false and PACKAGE_SET=minimal for dvd-iso
  templates.fif.json
Labels: test suite

#128 I once broke a bootloader needle
  needles/console/rocky-bootloader-bios-20210805.json
Labels: type: bug, test suite

#129 Fixing cockpit tests with new needles
  needles/cockpit/rocky-cockpit_updates_auto-20220724.json
  needles/cockpit/rocky-cockpit_updates_auto-20220724.png
  needles/cockpit/rocky-logs_entry_detail-priority-20220724.json
  needles/cockpit/rocky-logs_entry_detail-priority-20220724.png
  needles/gnome/rocky-getting-started-tour_close_button-20220705.json
  needles/gnome/rocky-getting-started-tour_close_button-20220705.png
  needles/gnome/rocky-getting-started-tour_next_button-20220705.json
  needles/gnome/rocky-getting-started-tour_next_button-20220705.png
  needles/gnome/rocky-getting-started-tour_start_button-20220705.json
  needles/gnome/rocky-getting-started-tour_start_button-20220705.png
  needles/gnome/rocky-getting_started_tour-20220705.json
  needles/gnome/rocky-getting_started_tour-20220705.png
Labels: tag: content, type: enhancement, test suite
