Repository rocky-linux/os-autoinst-distri-rocky, pull requests merged in 2023-03, with the labels that each got.

#155 Merge branch 'develop' into 'main'
  tests/_support_server.pm
Labels: priority: high, type: bug

#156 Modularity tests fix for 9.1 8.8 & 8.7
  needles/anaconda/install_destination/french/rocky-topbar_generic-20230222.json
  needles/anaconda/install_destination/french/rocky-topbar_generic-20230222.png
  needles/anaconda/install_process/rocky_do_install_and_reboot-prerelease_note-20230220.json
  needles/anaconda/install_process/rocky_do_install_and_reboot-prerelease_note-20230220.png
  needles/anaconda/install_process/rocky_do_install_and_reboot-version_8_ident-20230220.json
  needles/anaconda/install_process/rocky_do_install_and_reboot-version_8_ident-20230220.png
  needles/cockpit/rocky-server_cockpit_basic-cockpit_services_entry-20230221.json
  needles/cockpit/rocky-server_cockpit_basic-cockpit_services_entry-20230221.png
  needles/cockpit/rocky-server_cockpit_updates-cockpit_main-20230221.json
  needles/cockpit/rocky-server_cockpit_updates-cockpit_main-20230221.png
  tests/modularity_enable_disable_module.pm
  tests/modularity_install_module.pm
  tests/modularity_module_list.pm
Labels: type: bug, test suite

#157 Mirrorlist test changes for Issue #146
  templates.fif.json
Labels: type: bug, test suite

#160 Merge #156 and #157 to main
  needles/anaconda/install_destination/french/rocky-topbar_generic-20230222.json
  needles/anaconda/install_destination/french/rocky-topbar_generic-20230222.png
  needles/anaconda/install_process/rocky_do_install_and_reboot-prerelease_note-20230220.json
  needles/anaconda/install_process/rocky_do_install_and_reboot-prerelease_note-20230220.png
  needles/anaconda/install_process/rocky_do_install_and_reboot-version_8_ident-20230220.json
  needles/anaconda/install_process/rocky_do_install_and_reboot-version_8_ident-20230220.png
  needles/cockpit/rocky-server_cockpit_basic-cockpit_services_entry-20230221.json
  needles/cockpit/rocky-server_cockpit_basic-cockpit_services_entry-20230221.png
  needles/cockpit/rocky-server_cockpit_updates-cockpit_main-20230221.json
  needles/cockpit/rocky-server_cockpit_updates-cockpit_main-20230221.png
  templates.fif.json
  tests/modularity_enable_disable_module.pm
  tests/modularity_install_module.pm
  tests/modularity_module_list.pm
Labels: priority: medium, type: bug

#163 Anaconda text install (alternate)
  tests/_boot_to_anaconda.pm
  tests/install_text.pm
Labels: priority: medium, type: bug

#168 Serial console install
  tests/_boot_to_anaconda.pm
Labels: priority: medium, type: bug, test suite
