Repository rocky-linux/os-autoinst-distri-rocky, pull requests merged in 2023-05, with the labels that each got.

#170 Use pandoc-common instead of python3-kickstart for package tests
  lib/packagetest.pm
  tests/base_update_cli.pm
Labels: priority: medium, type: bug

#172 add support to specify dnf releasever during POST
  VARIABLES.md
  tests/_do_install_and_reboot.pm
Labels: priority: high, type: enhancement

#171 use Rocky Linux controlled openqa-testrepo-1
  lib/packagetest.pm
Labels: priority: medium, type: enhancement

#173 merge develop to main
  VARIABLES.md
  lib/packagetest.pm
  tests/_boot_to_anaconda.pm
  tests/_do_install_and_reboot.pm
  tests/base_update_cli.pm
Labels: priority: high

#177 r8.8 needles for cockpit
  needles/anaconda/help/rocky-anaconda_help_keyboard_layout-20230504.json
  needles/anaconda/help/rocky-anaconda_help_keyboard_layout-20230504.png
  needles/anaconda/help/rocky-anaconda_help_language_support-20230504.json
  needles/anaconda/help/rocky-anaconda_help_language_support-20230504.png
  needles/anaconda/help/rocky-anaconda_help_localization_link-20230504.json
  needles/anaconda/help/rocky-anaconda_help_localization_link-20230504.png
  needles/anaconda/help/rocky-anaconda_help_time_date-20230504.json
  needles/anaconda/help/rocky-anaconda_help_time_date-20230504.png
  needles/anaconda/help/rocky-help_language_selection-20230504.json
  needles/anaconda/help/rocky-help_language_selection-20230504.png
  needles/cockpit/rocky-cockpit_autoupdate_planned_time-20230507.json
  needles/cockpit/rocky-cockpit_autoupdate_planned_time-20230507.png
  needles/cockpit/rocky-cockpit_logs-20230507.json
  needles/cockpit/rocky-cockpit_logs-20230507.png
  needles/cockpit/rocky-cockpit_services_detail-20230507.json
  needles/cockpit/rocky-cockpit_services_detail-20230507.png
  needles/cockpit/rocky-cockpit_updates_all_install-20230507.json
  needles/cockpit/rocky-cockpit_updates_all_install-20230507.png
Labels: priority: medium, type: maintenance, test suite

#180 Merge develop to main
  needles/anaconda/help/rocky-anaconda_help_keyboard_layout-20230504.json
  needles/anaconda/help/rocky-anaconda_help_keyboard_layout-20230504.png
  needles/anaconda/help/rocky-anaconda_help_language_support-20230504.json
  needles/anaconda/help/rocky-anaconda_help_language_support-20230504.png
  needles/anaconda/help/rocky-anaconda_help_localization_link-20230504.json
  needles/anaconda/help/rocky-anaconda_help_localization_link-20230504.png
  needles/anaconda/help/rocky-anaconda_help_localization_link-20230513.json
  needles/anaconda/help/rocky-anaconda_help_localization_link-20230513.png
  needles/anaconda/help/rocky-anaconda_help_time_date-20230504.json
  needles/anaconda/help/rocky-anaconda_help_time_date-20230504.png
  needles/anaconda/help/rocky-help_language_selection-20230504.json
  needles/anaconda/help/rocky-help_language_selection-20230504.png
  needles/anaconda/install_process/arabic/rocky-anaconda_install_user_created-20230513.json
  needles/anaconda/install_process/arabic/rocky-anaconda_install_user_created-20230513.png
  needles/anaconda/install_process/japanese/rocky-install_done_reboot_japanese-20230513.json
  needles/anaconda/install_process/japanese/rocky-install_done_reboot_japanese-20230513.png
  needles/anaconda/install_process/russian/rocky-anaconda_install_user_created-20230513.json
  needles/anaconda/install_process/russian/rocky-anaconda_install_user_created-20230513.png
  needles/anaconda/main_hub/arabic/rocky-anaconda_main_hub_network_host_name_connected-20230513.json
  needles/anaconda/main_hub/arabic/rocky-anaconda_main_hub_network_host_name_connected-20230513.png
  needles/anaconda/main_hub/french/rocky-anaconda_main_hub_network_host_name_connected-20230513.json
  needles/anaconda/main_hub/french/rocky-anaconda_main_hub_network_host_name_connected-20230513.png
  needles/anaconda/main_hub/japanese/rocky-anaconda_main_hub_network_host_name_connected-20230513.json
  needles/anaconda/main_hub/japanese/rocky-anaconda_main_hub_network_host_name_connected-20230513.png
  needles/anaconda/main_hub/rocky-anaconda_main_hub_network_host_name_connected-20230513.json
  needles/anaconda/main_hub/rocky-anaconda_main_hub_network_host_name_connected-20230513.png
  needles/anaconda/main_hub/russian/rocky-anaconda_main_hub_network_host_name_connected-20230513.json
  needles/anaconda/main_hub/russian/rocky-anaconda_main_hub_network_host_name_connected-20230513.png
  needles/anaconda/universal/arabic/rocky-spoke_done_arabic-untranslated-20230513.json
  needles/anaconda/universal/arabic/rocky-spoke_done_arabic-untranslated-20230513.png
  needles/anaconda/universal/russian/rocky-spoke_done_russian-20230513.json
  needles/anaconda/universal/russian/rocky-spoke_done_russian-20230513.png
  needles/cockpit/rocky-cockpit_autoupdate_planned_time-20230507.json
  needles/cockpit/rocky-cockpit_autoupdate_planned_time-20230507.png
  needles/cockpit/rocky-cockpit_logs-20230507.json
  needles/cockpit/rocky-cockpit_logs-20230507.png
  needles/cockpit/rocky-cockpit_services_detail-20230507.json
  needles/cockpit/rocky-cockpit_services_detail-20230507.png
  needles/cockpit/rocky-cockpit_updates_all_install-20230507.json
  needles/cockpit/rocky-cockpit_updates_all_install-20230507.png
  needles/console/rocky-boot_enter_passphrase-20230513.json
  needles/console/rocky-boot_enter_passphrase-20230513.png
  needles/console/rocky-bootloader_uefi-20230513.json
  needles/console/rocky-bootloader_uefi-20230513.png
  needles/gnome/japanese/rocky-getting_started-20230513.json
  needles/gnome/japanese/rocky-getting_started-20230513.png
  scripts/run-all-flavors.sh
  scripts/run-openqa-tests.sh
  tests/_boot_to_anaconda.pm
Labels: priority: high, test suite

#182 task: merge develop to main
  needles/cockpit/rocky-autoupdate_planned_time-20230517.json
  needles/cockpit/rocky-autoupdate_planned_time-20230517.png
  needles/cockpit/rocky-cockpit_services_detail-20230517.json
  needles/cockpit/rocky-cockpit_services_detail-20230517.png
  needles/cockpit/rocky-logs-20230517.json
  needles/cockpit/rocky-logs-20230517.png
Labels: priority: medium, type: enhancement

#176 consider Rocky Linux version when adding powertools/crb
  tests/base_update_cli.pm
Labels: priority: medium, type: bug
